export const ROUTES = {
  HOME: '/',
  ABOUT: '/about',
  STORY: '/story',
  JOURNAL: '/journal',
  JOURNAL_ARTICLE: (slug: string) => '/journal/' + slug,
  CATEGORIES: '/categories',
  CATEGORY: (slug: string) => '/categories/' + slug,
  COLLECTIONS: '/collections',
  COLLECTION: (slug: string) => '/collections/' + slug,
  GUILDS: '/guilds',
  GUILD: (slug: string) => '/guilds/' + slug,
  SHOP: '/shop',
  PRODUCT: (slug: string) => '/shop/' + slug,
  SEARCH: '/search',
  WISHLIST: '/wishlist',
  CART: '/cart',
  CHECKOUT: '/checkout',
  ORDER_SUCCESS: '/checkout/success',
  ACCOUNT: '/account',
  ORDERS: '/account/orders',
  ORDER: (code: string) => '/account/orders/' + code,
  PROFILE: '/account/profile',
  SETTINGS: '/account/settings',
  LOGIN: '/auth/login',
  SIGNUP: '/auth/signup',
  FORGOT: '/auth/forgot',
  CONTACT: '/contact',
  FAQ: '/faq',
  SHIPPING: '/shipping',
  RETURNS: '/returns',
  TERMS: '/terms',
  PRIVACY: '/privacy',
  SUSTAINABILITY: '/sustainability',
  GI_REGISTRY: '/gi-registry',
} as const;

export const PRIMARY_NAV = [
  { label: 'Shop', href: ROUTES.SHOP },
  { label: 'Guilds', href: ROUTES.GUILDS },
  { label: 'Journal', href: ROUTES.JOURNAL },
  { label: 'Story', href: ROUTES.STORY },
] as const;

export const CATEGORY_STRIP = [
  { label: 'Phanek', href: '/categories/phanek' },
  { label: 'Longpi', href: '/categories/longpi' },
  { label: 'Kauna', href: '/categories/kauna' },
  { label: 'Muga', href: '/categories/muga' },
  { label: 'Cane & Bamboo', href: '/categories/cane-bamboo' },
  { label: 'Wood', href: '/categories/wood' },
] as const;
